apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deploy
  namespace: vkpaints-dev-ns
spec:
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-container
        image: shubha20/vk-paints_order-service:v1.0.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: order-config
        # - secretRef:
        #     name: order-secret
        ports:
        - containerPort: 3000
