apiVersion: v1
kind: Secret
metadata:
  name: order-service-secret
  namespace: vkpaints-dev-ns
type: Opaque
stringData:
  DB_URL: "postgres://postgres:postgres@postgres:5432/order_db"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
